[2023-09-02T22:09:01.819+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagemail.sendemail manual__2023-09-02T22:08:32.762713+00:00 [queued]>
[2023-09-02T22:09:01.829+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagemail.sendemail manual__2023-09-02T22:08:32.762713+00:00 [queued]>
[2023-09-02T22:09:01.830+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-02T22:09:01.830+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-09-02T22:09:01.830+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-02T22:09:01.844+0000] {taskinstance.py:1300} INFO - Executing <Task(EmailOperator): sendemail> on 2023-09-02 22:08:32.762713+00:00
[2023-09-02T22:09:01.848+0000] {standard_task_runner.py:55} INFO - Started process 1852 to run task
[2023-09-02T22:09:01.852+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dagemail', 'sendemail', 'manual__2023-09-02T22:08:32.762713+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/dagemail.py', '--cfg-path', '/tmp/tmpj9znsqe0']
[2023-09-02T22:09:01.852+0000] {standard_task_runner.py:83} INFO - Job 252: Subtask sendemail
[2023-09-02T22:09:01.918+0000] {task_command.py:388} INFO - Running <TaskInstance: dagemail.sendemail manual__2023-09-02T22:08:32.762713+00:00 [running]> on host 8d5456a88302
[2023-09-02T22:09:01.989+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=eternoaprendiz015@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dagemail
AIRFLOW_CTX_TASK_ID=sendemail
AIRFLOW_CTX_EXECUTION_DATE=2023-09-02T22:08:32.762713+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-02T22:08:32.762713+00:00
[2023-09-02T22:09:02.000+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:152: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-09-02T22:09:02.000+0000] {configuration.py:663} WARNING - section/key [smtp/smtp_user] not found in config
[2023-09-02T22:09:02.001+0000] {email.py:268} INFO - Email alerting: attempt 1
[2023-09-02T22:09:03.733+0000] {email.py:280} INFO - Sent an alert email to ['eternoaprendiz015@gmail.com']
[2023-09-02T22:09:04.516+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 281, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/local/lib/python3.7/smtplib.py", line 872, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError o19-20020a0568080f9300b003a88f5ebfeesm3417838oiw.42 - gsmtp', '***')
[2023-09-02T22:09:04.524+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dagemail, task_id=sendemail, execution_date=20230902T220832, start_date=20230902T220901, end_date=20230902T220904
[2023-09-02T22:09:04.536+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 252 for task sendemail ((530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError o19-20020a0568080f9300b003a88f5ebfeesm3417838oiw.42 - gsmtp', '***'); 1852)
[2023-09-02T22:09:04.550+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-02T22:09:04.572+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
