[2023-09-02T22:08:56.815+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagemail.tsk4 manual__2023-09-02T22:08:32.762713+00:00 [queued]>
[2023-09-02T22:08:56.825+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagemail.tsk4 manual__2023-09-02T22:08:32.762713+00:00 [queued]>
[2023-09-02T22:08:56.825+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-02T22:08:56.825+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-09-02T22:08:56.825+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-02T22:08:56.841+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2023-09-02 22:08:32.762713+00:00
[2023-09-02T22:08:56.846+0000] {standard_task_runner.py:55} INFO - Started process 1849 to run task
[2023-09-02T22:08:56.850+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dagemail', 'tsk4', 'manual__2023-09-02T22:08:32.762713+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/dagemail.py', '--cfg-path', '/tmp/tmp7fk2mijd']
[2023-09-02T22:08:56.850+0000] {standard_task_runner.py:83} INFO - Job 251: Subtask tsk4
[2023-09-02T22:08:56.910+0000] {task_command.py:388} INFO - Running <TaskInstance: dagemail.tsk4 manual__2023-09-02T22:08:32.762713+00:00 [running]> on host 8d5456a88302
[2023-09-02T22:08:56.974+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=eternoaprendiz015@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dagemail
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2023-09-02T22:08:32.762713+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-02T22:08:32.762713+00:00
[2023-09-02T22:08:56.976+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-09-02T22:08:56.976+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-09-02T22:08:56.988+0000] {subprocess.py:86} INFO - Output:
[2023-09-02T22:08:56.991+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-02T22:08:57.002+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-02T22:08:57.006+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dagemail, task_id=tsk4, execution_date=20230902T220832, start_date=20230902T220856, end_date=20230902T220857
[2023-09-02T22:08:57.024+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:152: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-09-02T22:08:57.024+0000] {configuration.py:663} WARNING - section/key [smtp/smtp_user] not found in config
[2023-09-02T22:08:57.024+0000] {email.py:268} INFO - Email alerting: attempt 1
[2023-09-02T22:08:58.917+0000] {email.py:280} INFO - Sent an alert email to ['eternoaprendiz015@gmail.com']
[2023-09-02T22:08:59.562+0000] {configuration.py:663} WARNING - section/key [smtp/smtp_user] not found in config
[2023-09-02T22:08:59.563+0000] {email.py:268} INFO - Email alerting: attempt 1
[2023-09-02T22:09:00.408+0000] {email.py:280} INFO - Sent an alert email to ['eternoaprendiz015@gmail.com']
[2023-09-02T22:09:01.066+0000] {taskinstance.py:1831} ERROR - Failed to send email to: ['eternoaprendiz015@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1520, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1581, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2231, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 281, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/local/lib/python3.7/smtplib.py", line 872, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError v8-20020a056830140800b006b9e81d94a7sm3145183otp.70 - gsmtp', '***')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1829, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2233, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 281, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/local/lib/python3.7/smtplib.py", line 872, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError x3-20020a9d6d83000000b006b9348b6f51sm3156141otp.54 - gsmtp', '***')
[2023-09-02T22:09:01.081+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 251 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 1849)
[2023-09-02T22:09:01.114+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-02T22:09:01.143+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
