[2023-08-28T20:19:21.304+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag2.tsk1 manual__2023-08-28T20:19:20.271697+00:00 [queued]>
[2023-08-28T20:19:21.315+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag2.tsk1 manual__2023-08-28T20:19:20.271697+00:00 [queued]>
[2023-08-28T20:19:21.316+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-08-28T20:19:21.316+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-08-28T20:19:21.317+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-08-28T20:19:21.335+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2023-08-28 20:19:20.271697+00:00
[2023-08-28T20:19:21.340+0000] {standard_task_runner.py:55} INFO - Started process 5341 to run task
[2023-08-28T20:19:21.348+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdag2', 'tsk1', 'manual__2023-08-28T20:19:20.271697+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/triggerdag2.py', '--cfg-path', '/tmp/tmp0qvprlfz']
[2023-08-28T20:19:21.348+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask tsk1
[2023-08-28T20:19:21.425+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdag2.tsk1 manual__2023-08-28T20:19:20.271697+00:00 [running]> on host c709185060f0
[2023-08-28T20:19:21.510+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdag2
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2023-08-28T20:19:20.271697+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-28T20:19:20.271697+00:00
[2023-08-28T20:19:21.512+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-28T20:19:21.513+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-08-28T20:19:21.526+0000] {subprocess.py:86} INFO - Output:
[2023-08-28T20:19:21.528+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-28T20:19:21.538+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-28T20:19:21.543+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerdag2, task_id=tsk1, execution_date=20230828T201920, start_date=20230828T201921, end_date=20230828T201921
[2023-08-28T20:19:21.559+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 5341)
[2023-08-28T20:19:21.600+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-08-28T20:19:21.621+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
